CREATE TABLE users(
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      username VARCHAR(20) NOT NULL,
                      password VARCHAR(255) NOT NULL

);

CREATE TABLE messages(
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         content TEXT NOT NULL,
                         date_of_send DATE NOT NULL,
                         is_edited BOOLEAN NOT NULL,
                         user_id INTEGER,
                         CONSTRAINT fk_messages_user
                             FOREIGN KEY (user_id)
                                 REFERENCES users(id)
                                 ON DELETE SET NULL
);

CREATE TABLE images(
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       image_name TEXT NOT NULL,
                       image_data bytea,
                       image_type TEXT,
                       message_id INTEGER,
                       CONSTRAINT fk_images_message
                           FOREIGN KEY (message_id)
                               REFERENCES group_messages (id)
                               ON DELETE CASCADE
);




CREATE TABLE groups (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL ,
                        description TEXT,
                        avatar BYTEA,
                        avatar_file_name VARCHAR(255),
                        avatar_file_type VARCHAR(100),
                        date_of_create DATE NOT NULL ,
                        admin_id INTEGER,

                        CONSTRAINT fk_group_admin
                            FOREIGN KEY (admin_id)
                                REFERENCES users(id)
                                ON DELETE SET NULL
);



CREATE TABLE group_moderators (
                                  group_id INTEGER NOT NULL,
                                  user_id INTEGER NOT NULL,

                                  PRIMARY KEY (group_id, user_id),

                                  CONSTRAINT fk_mod_group
                                      FOREIGN KEY (group_id)
                                          REFERENCES groups(id)
                                          ON DELETE CASCADE,

                                  CONSTRAINT fk_mod_user
                                      FOREIGN KEY (user_id)
                                          REFERENCES users(id)
                                          ON DELETE CASCADE
);




CREATE TABLE group_participants (
                                    group_id INTEGER NOT NULL,
                                    user_id INTEGER NOT NULL,

                                    PRIMARY KEY (group_id, user_id),

                                    CONSTRAINT fk_part_group
                                        FOREIGN KEY (group_id)
                                            REFERENCES groups(id)
                                            ON DELETE CASCADE,

                                    CONSTRAINT fk_part_user
                                        FOREIGN KEY (user_id)
                                            REFERENCES users(id)
                                            ON DELETE CASCADE
);



ALTER TABLE group_messages ADD COLUMN group_id INTEGER;



CREATE TABLE user_blacklist(
    user_id INTEGER NOT NULL,
    blocked_user_id INTEGER NOT NULL,

    PRIMARY KEY (user_id, blocked_user_id),


        CONSTRAINT fk_user
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,


    CONSTRAINT fk_blocked_user
        FOREIGN KEY (blocked_user_id)
            REFERENCES users(id)
            ON DELETE CASCADE


);



CREATE TABLE directs(
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        sender_id INTEGER NOT NULL,
                        recipient_id INTEGER NOT NULL,

                        date_of_start DATE NOT NULL,

                        CONSTRAINT uq_direct UNIQUE(sender_id, recipient_id),

                        CONSTRAINT fk_sender_user
                            FOREIGN KEY(sender_id)
                                REFERENCES users(id)
                                ON DELETE CASCADE,

                        CONSTRAINT fk_recipient_user
                            FOREIGN KEY(recipient_id)
                                REFERENCES users(id)
                                ON DELETE CASCADE
);
