CREATE TABLE users(
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      username VARCHAR(20) NOT NULL,
                      password VARCHAR(255) NOT NULL

);

CREATE TABLE messages(
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         content TEXT NOT NULL,
                         date_of_send DATE NOT NULL,
                         is_edited BOOLEAN NOT NULL,
                         user_id INTEGER,
                         CONSTRAINT fk_messages_user
                             FOREIGN KEY (user_id)
                                 REFERENCES users(id)
                                 ON DELETE SET NULL
);

CREATE TABLE images(
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       image_name TEXT NOT NULL,
                       image_data bytea,
                       image_type TEXT,
                       message_id INTEGER,
                       CONSTRAINT fk_images_message
                           FOREIGN KEY (message_id)
                               REFERENCES messages(id)
                               ON DELETE CASCADE
);